#!/usr/bin/python

import requests as req
from bs4 import BeautifulSoup
import json

URL = 'https://pt.wikipedia.org/wiki/Ariquemes'

r = req.get(URL)
soup = BeautifulSoup(r.content, features="html5lib")
#print(soup.prettify())

title = soup.h1
#print(title)
#print(soup.img)

tables = soup.find_all('table')
#print(len(tables))
#print(tables[1]['style'])

lists = soup.find_all('li')
#print(len(lists))

childs = list(lists[3].children)
#print(len(childs))

links = soup.find_all('a')
#print(len(links))

attr_filter = {"class": "mw-jump-link", "href": "#mw-head"}
#print(len(soup.find_all('a', attr_filter)))

attr_filter = {'class': 'noprint'}
#print(len(soup.find_all(None, attr_filter)))

attr_filter = {'class': 'fn'}
#print(len(soup.find_all(None, attr_filter)))

attr_filter = {'id': 'firstHeading'}
#print(len(soup.find_all(None, attr_filter)))

selector = '.thumbimage'
#print(soup.select(selector, limit=3))


api_link = 'https://jsonplaceholder.typicode.com/posts'

input_data = json.dumps({'title': 'test title', 'user_id': 5})
headers = {'Content-Type': 'application/json'}
r = req.post(api_link, input_data, headers = headers)
data = json.loads(r.content)
print(data)


link = 'http://testing-ground.scraping.pro/login'

LOGGED_SELECTOR = '#case_login'

def is_logged(html_source):
    soup = BeautifulSoup(html_source, features="html5lib")
    elements = soup.select(LOGGED_SELECTOR)
    if len(elements) == 1:
        element = elements[0]
        if 'success' in element.get('class', []):
            return True
        else:
            return False
    elif len(elements) > 1:
        raise Exception('Something is wrong with the source')
    else:
        return False

input_data = {'usr': 'admin', 'pwd': '12345'}

r_post = req.post(link+'?mode=login', input_data)
r_get = req.get(link+'?mode=welcome')

print(is_logged(r_post.content))
print(is_logged(r_get.content))

s = req.Session()
r_post = s.post(link+'?mode=login', input_data)
r_get = s.get(link+'?mode=welcome')

print(is_logged(r_get.content))
